[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "napari-tyssue"
dynamic = ["version"]
description = "A napari plugin for use with the tyssue library"
readme = "README.md"
license = { text = "BSD-3-Clause" }
authors = [
    { name = "Kyle Harrington", email = "czi@kyleharrington.com" },
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: napari",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Image Processing",
]
dependencies = [
    "numpy",
    "magicgui",
    "qtpy",
    "tyssue",
    "quantities",
    "pooch",
    "tables",
    "imageio-ffmpeg",
    "invagination==0.0.2",
]

[project.optional-dependencies]
testing = [
    "tox",
    "pytest",
    "pytest-cov",
    "pytest-qt",
    "napari",
    "pyqt5",
    "matplotlib",
]

[project.urls]
"Bug Tracker" = "https://github.com/kephale/napari-tyssue/issues"
"Documentation" = "https://github.com/kephale/napari-tyssue#README.md"
"Source Code" = "https://github.com/kephale/napari-tyssue"
"User Support" = "https://github.com/kephale/napari-tyssue/issues"

[project.entry-points."napari.manifest"]
napari-tyssue = "napari_tyssue:napari.yaml"

[tool.setuptools]
package-dir = { "" = "src" }
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.yaml"]

[tool.setuptools.dynamic]
version = { attr = "napari_tyssue.__version__" }

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79
